#!/usr/bin/env bash -e

# newline print
nl_print() {
	printf "\n$1\n"
}

nl_print "WARNING 1: The transfer process shouldn't take longer than 5 minutes. If it does, something may be wrong."
nl_print "WARNING 2: Are both drives connected directly to the computer? e.g. not via USB hub [y/n]"

read -n 1 input

if [[ ! ( "$input" == "y" || "$input" == "Y" || "$input" == "" ) ]]
then
	nl_print "Please connect both drives directly to the computer and restart this script."
	exit 1
fi


SOURCE_DISK="/Volumes/1TB Emil SSD"
TARGET_DISK="/Volumes/2TB Emil Backup"

# ! -perm -o=r 			### find files which 'other' users don't have read permission for
# -a -maxdepth 1 		### traverse a maximum depth of 1 (top level of directory)
# -execdir echo {} ';' 	### remove preceding filepath from each entry. E.G. /Volumes/1TB Emil SSD/.Spotlight-V100 -> .Spotlight-V100

UNREADABLE_DIRECTORIES=$(find "$SOURCE_DISK" ! -perm -o=r -a -maxdepth 1 -execdir echo {} ';')

check_disk_is_connected () {
	DISK_NAME=$1

	if [[ ! -d "$DISK_NAME" ]] 
	then
		nl_print "$DISK_NAME disk was not found. Aborting"
		exit 1
	fi
}

check_disk_is_connected "$SOURCE_DISK"
check_disk_is_connected "$TARGET_DISK"

sudo rsync -avE --delete --progress --exclude-from="-" "$SOURCE_DISK/" "$TARGET_DISK/" <<< "$UNREADABLE_DIRECTORIES"